"""
schema.py

Typed schemas for the main model-ready datasets.

These Pydantic models are intentionally simple:
- numeric fields use float | int where appropriate
- optional fields are allowed as None
- they match the *spirit* of the model_*.csv files created
  in data/prepared data/model_ready/.

Your teammate can import these in a notebook or API, e.g.:

    from src.schema import BranchDailyOpsRow, BranchMasterRow
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


# -------------------------------------------------------------------
# Common small types
# -------------------------------------------------------------------

class BranchBase(BaseModel):
    branch: str = Field(..., description="Branch name, e.g. 'Conut - Tyre'")


# -------------------------------------------------------------------
# 1) Branch-level master features (model_branch_master.csv)
# -------------------------------------------------------------------

class BranchMasterRow(BranchBase):
    vat_11_percent: float = Field(..., description="VAT 11% value or rate")
    total_revenue: float = Field(..., description="Total revenue over the horizon")
    min_monthly_sales: float = Field(..., description="Minimum monthly sales")
    max_monthly_sales: float = Field(..., description="Maximum monthly sales")
    std_monthly_sales: float = Field(..., description="Std. dev of monthly sales")
    avg_monthly_growth: float = Field(..., description="Average monthly growth rate")


# -------------------------------------------------------------------
# 2) Branch daily operations (model_branch_daily_ops.csv)
# -------------------------------------------------------------------

class BranchDailyOpsRow(BranchBase):
    date: str = Field(..., description="Date in YYYY-MM-DD")
    num_employees: int = Field(..., description="Number of employees who worked")
    total_work_hours: float = Field(..., description="Total worked hours that day")
    max_monthly_sales: Optional[float] = Field(
        None, description="Branch max monthly sales (joined feature)"
    )
    min_monthly_sales: Optional[float] = Field(
        None, description="Branch min monthly sales (joined feature)"
    )
    std_monthly_sales: Optional[float] = Field(
        None, description="Branch std monthly sales (joined feature)"
    )
    avg_monthly_growth: Optional[float] = Field(
        None, description="Branch average monthly growth (joined feature)"
    )


# -------------------------------------------------------------------
# 3) Customer-level table (model_customers.csv)
# -------------------------------------------------------------------

class CustomerRow(BaseModel):
    customer_name: str
    phone: Optional[str] = None
    first_order: Optional[str] = Field(
        None, description="First order date (YYYY-MM-DD or datetime string)"
    )
    last_order: Optional[str] = Field(
        None, description="Last order date (YYYY-MM-DD or datetime string)"
    )
    avg_order_value: Optional[float] = None
    is_one_time_customer: Optional[int] = Field(
        None, description="1 if only one order, else 0"
    )
    recency_days: Optional[float] = Field(
        None, description="Days since last order at snapshot date"
    )
    is_high_value_customer: Optional[int] = Field(
        None, description="1 if above RFM threshold, else 0"
    )


# -------------------------------------------------------------------
# 4) Item group level (model_item_groups.csv)
# -------------------------------------------------------------------

class ItemGroupRow(BranchBase):
    division: str
    group: str
    group_rank_in_branch: Optional[float] = Field(
        None, description="Rank of this group inside branch by sales"
    )
    is_top3_group_in_branch: Optional[int] = Field(
        None, description="1 if this group is in the top-3 in the branch"
    )
    group_sales_share_in_branch: Optional[float] = Field(
        None, description="Share of branch revenue generated by this group"
    )


# -------------------------------------------------------------------
# 5) Sales detail level (model_sales_detail.csv)
# -------------------------------------------------------------------

class SalesDetailRow(BranchBase):
    customer_name: str
    price_line_total: float = Field(..., description="Line total amount")
    item_category: Optional[str] = Field(
        None, description="High-level category, e.g. milkshake / coffee / other"
    )
    is_milkshake: Optional[int] = 0
    is_coffee: Optional[int] = 0
    is_core_beverage: Optional[int] = 0


# -------------------------------------------------------------------
# 6) Menu level (model_avg_menu.csv)
# -------------------------------------------------------------------

class AvgMenuRow(BranchBase):
    menu_type: str = Field(..., description="Menu type, e.g. DELIVERY / TAKE AWAY")
    customer_count: Optional[float] = None
    total_sales: Optional[float] = None
    sales_share_in_branch: Optional[float] = None
    customer_share_in_branch: Optional[float] = None
    is_premium_menu_in_branch: Optional[int] = None


# -------------------------------------------------------------------
# 7) Division level (model_divisions.csv)
# -------------------------------------------------------------------

class DivisionRow(BranchBase):
    division: str
    delivery: Optional[float] = Field(None, description="Delivery share or count")
    table_share: Optional[float] = None
    takeaway_share: Optional[float] = None
    division_rank_in_branch: Optional[float] = None
    is_top3_division_in_branch: Optional[int] = None


# -------------------------------------------------------------------
# Convenience unions for type hints
# -------------------------------------------------------------------

ModelRow = BranchMasterRow | BranchDailyOpsRow | CustomerRow | ItemGroupRow | SalesDetailRow | AvgMenuRow | DivisionRow
SALES_COLUMNS = [
    "date",
    "branch_id",
    "item_name",
    "category",
    "quantity",
    "revenue"
]

ATTENDANCE_COLUMNS = [
    "date",
    "branch_id",
    "employee_id",
    "shift",
    "hours"
]
